### ISSUE TITLE
Secure WebSocket Relay connection working with W600 flawlessly. Minor issue.

### ISSUE THREAD

**Issue by rkompass** [vshymanskyy/ViperIDE#13]
Hello Volodymyr,

A first feedback, as you invited/requested:

I tested the new WebSocket Relay connection with the latest w600 firmware (and Brave) and it works flawlessly.
Of course there is a little bit less memory available now, but we have enough of it :-)
Also the repl is a bit slower, which makes sense.
I like the flicker of the webrepl symbol while transferring (saving, e.g.) files.
Also it's nice to have the _run_ triangle getting red while executing a script!

A minor issue, which was probably already there at the web_repl:
When changing a script, after saving, there is still the old size of it displayed in the directory view.
I have to switch to package manager display and back to directory tree display to get the updated size, which is annoying.

**Comment by rkompass** [comment]
More feedback:
Positive:
With the wss_repl all my browsers seem to work (now also Opera and Chromium on Manjaro Linux).

**Comment by vshymanskyy** [comment]
Thanks for the feedback. Yes the file size is not updated currently. It's not easy to fix though...

**Comment by vshymanskyy** [comment]
We can free some memory by moving the websocket client implementation to native code.

**Comment by vshymanskyy** [comment]
With the recent changes, you'll need to reinstall the `viper-tools`. There are some breaking changes

**Comment by vshymanskyy** [comment]
Should be fixed now
