### ISSUE TITLE
ViperIDE with WebAssembly MP does not let you create directory at file creation dialog

### ISSUE THREAD

**Issue by rkompass** [vshymanskyy/ViperIDE#15]
**Describe the bug**
[ViperIDE with WebAssembly](https://viper-ide.org/?emulator=1) MP does not let you create directory at file creation dialog.
Pressing the + beneath a directory in the file manager panel and entering  a name with / leads to an error:
```
 File "<stdin>", line 5, in <module>
OSError: 20
```
in a red box at the top right.
While simple file creation or deletion (using + or x) works!

**Setup**
 - MicroPython board: WebAssembly, as in [https://viper-ide.org/?vm=1](https://viper-ide.org/?vm=1)
 - MicroPython version: 1.24.0-preview.47
 - OS version: Linux
 - Browser: Brave, Chromium, Firefox
 - Connection type: none

**To Reproduce**
1. Open the above link in a new browser window.
2. Click in the file manager window the **+** besides the **tmp** directory and enter `tmpdir/` for example.

**Expected behavior**
Creation of the directory.

**Actual Screenshots / Logs**
![Screenshot_2024-07-16_17-47-23](https://github.com/user-attachments/assets/b5599f1a-3d2e-4f98-afcb-02599136c750)

**Additional context**
none

**Comment by vshymanskyy** [comment]
I reproduced it, working on a fix
