### ISSUE TITLE
Highlight open file better

### ISSUE THREAD

**Issue by ThinkTransit** [vshymanskyy/ViperIDE#16]
Hi,

Great project nice work! This is nit picking but it would be a nice change if you could increase the visibility of the current file that is open.

**Is your feature request related to a problem? Please describe.**
Feature request, it is a little bit difficult to see which file is open when working on large projects. For example in this screenshot I have main.py open but it is only slightly highlighted.

<img width="1919" alt="viperide" src="https://github.com/user-attachments/assets/0d2083dd-fa19-4b74-b5ce-1e86c2549bed">

**Describe the solution you'd like**
Could the text boldness be increased or the current open file name be shown somewhere.

**Comment by vshymanskyy** [comment]
Agree.

**Comment by vshymanskyy** [comment]
![image](https://github.com/user-attachments/assets/10ceecc1-f6bf-47f0-922a-51a034d443ec)
did this for now
