### ISSUE TITLE
Watch ttgo v2 : connect to USB single serial , listdir but no input keyboard

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#2]
Bonjour ,
Test on Android tablettes
Connect with esp32 board : KO
Connect with ttgo watch v1 : KO
Connect with ttgo watch v2 : OK , prompt '>>>' three Times , then listdir ('f:<file name>) ==> micropython 1.14
 but no input keyboard.
No file explorer.
No android copy/paste on the console , so no screenshots !
Also AT this moment ...no star

**Comment by vshymanskyy** [comment]
At this moment, no fixes for bugs with no clear description and steps to reproduce.

**Comment by vshymanskyy** [comment]
You should try again with  ttgo watch v2, it may have been fixed. also try using the latest micropython
