### ISSUE TITLE
🚀 Multi-tab file editor

### ISSUE THREAD

**Issue by vshymanskyy** [vshymanskyy/ViperIDE#28]
- [ ] Allow opening multiple files
- [ ] Highlight open files in File Manager
- [ ] Reuse File Manager: Switch between file editors using by selecting files
- [ ] Indicate unsaved files inf File Manager
- [ ] If an open file is deleted, the editor should switch to any open file
- [ ] Saving should be disabled for readonly and virtual files
- [ ] Bonus: do not reload main file (any files) from device if it has unsaved changes

**Comment by roseyangina** [comment]
Hello, I can see the file manager implemented in app.js. So then would app.js and app.css be the relevant files to make changes to here?
