### ISSUE TITLE
Block Comment/UnComment for multiple lines of Python code [new feature, or need documentation?]

### ISSUE THREAD

**Issue by DeeJay** [vshymanskyy/ViperIDE#29]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when... I need to temporarily Comment-out a block of code. Lines need to be '#' marked individually.

**Describe the solution you'd like**
After selecting a group of lines of code, being able to use a single keystroke to '#' Comment them (or UnComment them.)

**Describe alternatives you've considered**
Maybe this is already implemented in CodeMirror but I haven't found the relevant documentation for the  key-mappings?

**Comment by vshymanskyy** [comment]
Please try <kbd>Ctrl-/</kbd>
