### ISSUE TITLE
Disable save/download when sysinfo.md is selected

### ISSUE THREAD

**Issue by andypiper** [vshymanskyy/ViperIDE#31]
**Describe the bug**
Currently, if the sysinfo.md virtual file is selected in the file manager sidebar, and the user clicks the save or run buttons at the top, Viper reports a TypeError in a red popup.

**Setup**
 - MicroPython board: Pico W
 - MicroPython version: 1.23.0
 - OS version: macOS Sonoma
 - Browser: Chrome
 - Connection type: USB

**To Reproduce**
In description

**Expected behavior**
I would imagine it might be a good idea to disable these buttons?

**Actual Screenshots / Logs**
<img width="811" alt="Screenshot 2024-09-10 at 12 45 19" src="https://github.com/user-attachments/assets/537906c3-5767-4eef-99a5-f3d4b6b2e3cd">

**Comment by vshymanskyy** [comment]
Will be handled by https://github.com/vshymanskyy/ViperIDE/issues/28
