### ISSUE TITLE
whats new in .22 ??

### ISSUE THREAD

**Issue by littlegreenbean33** [vshymanskyy/ViperIDE#35]
His,

where can I see new improvements / bug fixing ?

**Comment by DeeJay** [comment]
The Commit history suggests it may be an updated version of something related to CSS.
[https://github.com/vshymanskyy/ViperIDE/commit/93adf20cafad2ec8f3eeb5d4b4738003ac9d1d1d](https://github.com/vshymanskyy/ViperIDE/commit/93adf20cafad2ec8f3eeb5d4b4738003ac9d1d1d)

**Comment by vshymanskyy** [comment]
The release history will not be maintained utill we reach 1000 monthly active users 👉👈

**Comment by vshymanskyy** [comment]
The full log of changes: https://github.com/vshymanskyy/ViperIDE/commits/main/
