### ISSUE TITLE
Vscode extension? 

### ISSUE THREAD

**Issue by Josverl** [vshymanskyy/ViperIDE#5]
I like the connectivity and package management, but the editor is very basic.

Have you considered using parts of the solution to create an adding for vscode which would combine your great work, with a great and popular IDE with all kinds of other integrations.

**Comment by vshymanskyy** [comment]
Right now there are no such plans. Viper IDE is simple, and it should remain so. The UI part of the IDE is focused on mobile/tablet use, and I think VSCode is not gonna cut it 

If there's someone willing to contribute to a vscode plugin, I'd be happy to participate.

**Comment by Josverl** [comment]
If that is your focus that is fine, and I'm sure if fills a need.
If I have time Ill take will remeber the good work,  and ping back here.
