### ISSUE TITLE
Blackpill : version of micropython needed for use on smartphone ?

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#6]
Bonjour ,
I read in #1 "I tested with a Blackpill board and it worked". ON Android ?
With  "MicroPython v1.22.0-preview.54.g95d8b5fd5.dirty on 2023-10-23" , blackpill not found.
Why fresh version ? New USB driver ? Hot to USB driver version with micropython script ?
( It's not easy to upgrade MP blackpill version for hobbyist on WeAct blackpill)
Thanks for info
Regard

**Comment by rkompass** [comment]
Hello @picpic020960,

[here](https://github.com/nspsck/STM32F411CEU6_BlackPill_Micropython/tree/main) are recent firmwares for the Blackpill.

**Comment by picpic020960** [comment]
I will test
ESP32-s3 : not found with fresh micropython on android and windows. Rrrr! The drivers !!!

**Comment by picpic020960** [comment]
Oooups : câble issue for blackpill : now it's OK
Awesone
