### ISSUE TITLE
file update 

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#8]
#Explorateur de fichiers OK AU début.
Charger le fichier OK mais enregistrer Après mise à jour KO : taille du fichier = 0
Nouveau fichier : enregistrer KO également Après reconnexion.

**Comment by vshymanskyy** [comment]
Please check with Viper IDE v0.3.2

**Comment by vshymanskyy** [comment]
Please check with Viper IDE v0.3.2
Yes this was a small regression in the recent change. Should be fixed now @picpic020960

**Comment by vshymanskyy** [comment]
Yes this was a small regression in the recent change. Should be fixed now

**Comment by vshymanskyy** [comment]
@picpic020960 can be closed?

**Comment by vshymanskyy** [comment]
The project is awaiting your github star 😂

**Comment by vshymanskyy** [comment]
@picpic020960 close?
