### ISSUE TITLE
improvement : zoom and proportionnal fonts  : it's better for eyes on android tablet

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#9]
[re]bonjour
all is in the subject.
big progress !

**Comment by vshymanskyy** [comment]
The request is unclear

**Comment by picpic020960** [comment]
Change the size of characters in file explorer window , update file window and console window.
Usefull for little screen of Android tablett
Thank's

**Comment by vshymanskyy** [comment]
Just sizes? Should be smaller?

**Comment by vshymanskyy** [comment]
@picpic020960 Zoom control was added
